### ISSUE TITLE
Italic comment for C++

### ISSUE THREAD

**Issue by branchus** [rakr/vim-one#48] opened 2017-05-05 10:54 UTC
Hi

really like your "one" color scheme. thank you!

I used Vim with one color scheme to edit a cpp file today, and noticed that the comments are not italic, italic comment works fine with other file types.

italic comment for C++ used to work. not sure what is going wrong, might be vim itself.

Can you have a look please?

Thanks
B

**Comment by rakr** [comment] 2017-05-05 11:33
Thanks! Appreciate you like this colorscheme.
The issue is not Vim, but a setting in the colorscheme that I just fixed. It's now fixed, let me know if that works properly.

**Comment by branchus** [comment] 2017-05-05 11:42
Hi rakr

Thank you for the quick fix.

Yes, I really like your one color scheme.

Thank you :)
B

**Comment by rakr** [comment] 2017-05-05 11:42
No worries, have a good one.

**Closed by rakr** 2017-05-05 11:42 UTC
Labels: fixed
